application:
  name: ktor-with-postgre-qovery-example
  project: ktor-with-postgre-qovery-example
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: my-postgresql-6132005
routers:
- name: main
  routes:
  - application_name: ktor-with-postgre-qovery-example
    paths:
    - /*
